<a href="https://colab.research.google.com/github/arshnoor08/Regression-Salary-Prediction/blob/main/Linear_Regression_Salary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("/content/Salary_Data.csv")
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [ ]:
data.info()

In [ ]:
# Divide the data into features and target
x = np.array(data.iloc[:][["YearsExperience"]])
#x = np.array(data.iloc[:,0])
#x = x.reshape(len(x),1)

In [ ]:
y = np.array(data.iloc[:,1])
y

In [ ]:
# Split the data into training and testing

In [ ]:
x_new = x[0:10]
y_new = y[0:10]
from sklearn.model_selection import train_test_split
a,b,c,d = train_test_split(x_new,y_new,train_size=0.70,random_state=1)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.80,random_state=4697)

In [ ]:
ytest

array([ 43525., 109431., 101302.,  81363., 122391.,  91738.])

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
model.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
### Test the model (Prediction)
ypred = model.predict(xtest)
ypred

array([ 44788.50460346, 107700.91806713, 100188.98810131,  81409.16318679,
       122724.77799875,  89860.08439832])

In [ ]:
xtest

array([[ 2. ],
       [ 8.7],
       [ 7.9],
       [ 5.9],
       [10.3],
       [ 6.8]])

In [ ]:
ytest

array([ 43525., 109431., 101302.,  81363., 122391.,  91738.])

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(ytest,ypred)
r2

0.9974925617006956

In [ ]:
### Plot the line of regression (Training)
plt.figure(figsize=(8,5))
plt.scatter(xtrain,ytrain,color='blue',s=100,label="Actual Point")
plt.scatter(xtrain,model.predict(xtrain),color='red',s=100,label="Predicted Point")
plt.plot(xtrain,model.predict(xtrain),linestyle='dotted',color='orange',label="Line of Regression")
plt.show()

In [ ]:
### Plot the line of regression (Testing)
plt.figure(figsize=(8,5))
plt.scatter(xtest,ytest,color='blue',s=100,label="Actual Point")
plt.scatter(xtest,model.predict(xtest),color='red',s=100,label="Predicted Point")
plt.plot(xtest,model.predict(xtest),linestyle='dotted',color='orange',label="Line of Regression")
plt.show()

In [ ]:
scores = []
for i in range(5000):
  xtrain1,xtest1,ytrain1,ytest1 = train_test_split(x,y,train_size=0.80,random_state=i)
  model1 = LinearRegression()
  model1.fit(xtrain1,ytrain1)
  ypred1 = model1.predict(xtest1)
  scores.append(r2_score(ytest1,ypred1))

In [ ]:
np.max(scores)

0.9974925617006956

In [ ]:
np.argmax(scores)

4697

In [ ]:
model.predict([[11]])

array([129297.71671883])

In [ ]:
years = float(input("Enter experience in years "))
salary = model.predict([[years]])
print("The salary is Rs "+str(salary[0]))

Enter experience in years 5
The salary is Rs 72958.24197524918


In [ ]:
print("The salary is Rs",str(salary[0]))

The salary is Rs 72958.24197524918


In [ ]:
print("The salary is Rs",end=" ")
print(str(salary[0]))

The salary is Rs 72958.24197524918


In [ ]:
file = open('output.txt','w')
file.write("The salary is Rs"+str(salary[0]))
file.close()

In [ ]:
m = model.coef_
c = model.intercept_

In [ ]:
print(m)

[9389.91245726]


In [ ]:
print(c)

26008.679688929536


In [ ]:
model.predict([[11]])

array([129297.71671883])